version: '3.8'
services:
  nextjs:
    build: .
    container_name: innoscripta-test
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules # Avoid overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ['yarn', 'dev']
